/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import classes.ProductDatabaseHandler;
import frame.MainFrame;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JButton;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author krzys
 */
public class FeaturePanel extends javax.swing.JPanel implements ListSelectionListener{

 
    private int width,heigth;
    private MainFrame mainFrame;
    private ProductDatabaseHandler productDatabaseHandler;
    
    Pattern pattern = Pattern.compile("[-]?[0-9]*\\.,?[0-9]+");
    Matcher matcher;
    
    double newPrice = 0, oldPrice = 0;
    String newPriceString = "";
    int amountOfProduct = 0, discount = 0;
    
    public FeaturePanel(MainFrame frame) {
        initComponents();
        this.mainFrame = frame;
        this.width = this.mainFrame.getElementTwoWidth();
        this.heigth = this.mainFrame.getElementTwoHeigth();
        this.setSize(width, heigth);
        
        exitButton.setText(mainFrame.getResourceBundle().getString("exit"));
        settingsButton.setText(mainFrame.getResourceBundle().getString("settings"));
        basketButton.setText(mainFrame.getResourceBundle().getString("basket"));
        comparisonButton.setText(mainFrame.getResourceBundle().getString("compareButton"));
        partsButton.setText(mainFrame.getResourceBundle().getString("mainPanel"));
        accessoriesButton.setText(mainFrame.getResourceBundle().getString("accessories"));
        discountSpinnerLabel.setText(mainFrame.getResourceBundle().getString("discountLabel"));
        menuLabel.setText(mainFrame.getResourceBundle().getString("menuLabel"));
        tabsLabel.setText(mainFrame.getResourceBundle().getString("tabsLabel"));
        acceptButton.setText(mainFrame.getResourceBundle().getString("accept"));
        backButton.setText(mainFrame.getResourceBundle().getString("erase"));
        addBasketButton.setText(mainFrame.getResourceBundle().getString("addBasket"));
        
        partsButton.addActionListener(mainFrame.getMenuPanel());
        exitButton.addActionListener(mainFrame.getMenuPanel());
        settingsButton.addActionListener(mainFrame.getMenuPanel());
        basketButton.addActionListener(mainFrame.getMenuPanel());
        comparisonButton.addActionListener(mainFrame.getMenuPanel());
        
        addBasketButton.setEnabled(false);
    }
    
    public void discountApply(){
                 amountOfProduct = this.mainFrame.getPartPanel().getJTable().getRowCount();
        
        for(int counter=0; counter < amountOfProduct; counter++){
            matcher = pattern.matcher((String)mainFrame.getMainPanel().getResearcher(this.mainFrame.getPartPanel().getResearcher().getShopName()).getProductDatabaseHandler().getPrice(counter));
            while(matcher.find()) oldPrice = Float.parseFloat(matcher.group());
            discount = 100 - (int)discountSpinner.getModel().getValue();
            newPrice = oldPrice * ((float)discount/100.0);
            newPriceString = "'" +  String.format("%.2f", newPrice) + "'";    
            //mainFrame.getMainPanel().getResearcher().getProductDatabaseHandler().updateElement(counter, newPriceString);
            mainFrame.getPartPanel().getJTable().getModel().setValueAt("" + newPrice,counter, 2);
            mainFrame.revalidate();
            mainFrame.repaint();
        }
    }
    
    public JButton getAddBasketButton(){
        return this.addBasketButton;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        partsButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        basketButton = new javax.swing.JButton();
        discountSpinnerLabel = new javax.swing.JLabel();
        discountSpinner = new javax.swing.JSpinner();
        accessoriesButton = new javax.swing.JButton();
        tabsLabel = new javax.swing.JLabel();
        menuLabel = new javax.swing.JLabel();
        comparisonButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        acceptButton = new javax.swing.JButton();
        addBasketButton = new javax.swing.JButton();

        partsButton.setText("jButton1");

        settingsButton.setText("jButton1");

        exitButton.setText("jButton1");

        basketButton.setText("jButton1");

        discountSpinnerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        discountSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        accessoriesButton.setText("jButton1");
        accessoriesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accessoriesButtonActionPerformed(evt);
            }
        });

        tabsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        menuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        comparisonButton.setText("jButton1");

        backButton.setText("jButton1");

        acceptButton.setText("jButton1");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        addBasketButton.setText("jButton1");
        addBasketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBasketButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(discountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(acceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addBasketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comparisonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accessoriesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discountSpinnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(basketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(discountSpinnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(discountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tabsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(partsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accessoriesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(menuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(basketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(addBasketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comparisonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(311, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setElementsEnabled(boolean value){
        this.acceptButton.setEnabled(value);
        this.backButton.setEnabled(value);
        discountSpinner.setEnabled(value);
    }
    
    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        discountApply();
    }//GEN-LAST:event_acceptButtonActionPerformed

    private void addBasketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBasketButtonActionPerformed
        mainFrame.getPartPanel().getAddBasketButton().doClick();
    }//GEN-LAST:event_addBasketButtonActionPerformed

    private void accessoriesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accessoriesButtonActionPerformed
        mainFrame.setActivePanel(mainFrame.getWearPanelLabel());
    }//GEN-LAST:event_accessoriesButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton accessoriesButton;
    private javax.swing.JButton addBasketButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton basketButton;
    private javax.swing.JButton comparisonButton;
    private javax.swing.JSpinner discountSpinner;
    private javax.swing.JLabel discountSpinnerLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JButton partsButton;
    private javax.swing.JButton settingsButton;
    private javax.swing.JLabel tabsLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void valueChanged(ListSelectionEvent e) {
        addBasketButton.setEnabled(true);
        //mainFrame.getPartPanel().getBasketButton().setEnabled(true);
    }
}
