/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import frame.MainFrame;

/**
 *
 * @author krzys
 */
public class FeaturePanel extends javax.swing.JPanel {

 
    private int width,heigth;
    private MainFrame mainFrame;
    
    
    public FeaturePanel(MainFrame frame) {
        initComponents();
        this.mainFrame = frame;
        this.width = this.mainFrame.getElementTwoWidth();
        this.heigth = this.mainFrame.getElementTwoHeigth();
        this.setSize(width, heigth);
        
        
        exitButton.setText(mainFrame.getResourceBundle().getString("exit"));
        settingsButton.setText(mainFrame.getResourceBundle().getString("settings"));
        basketButton.setText(mainFrame.getResourceBundle().getString("basket"));
        comparisonButton.setText(mainFrame.getResourceBundle().getString("compareButton"));
        partsButton.setText(mainFrame.getResourceBundle().getString("mainPanel"));
        accessoriesButton.setText(mainFrame.getResourceBundle().getString("accessories"));
        discountSpinnerLabel.setText(mainFrame.getResourceBundle().getString("discountLabel"));
        menuLabel.setText(mainFrame.getResourceBundle().getString("menuLabel"));
        tabsLabel.setText(mainFrame.getResourceBundle().getString("tabsLabel"));
        acceptButton.setText(mainFrame.getResourceBundle().getString("accept"));
        backButton.setText(mainFrame.getResourceBundle().getString("erase"));
        
        
        partsButton.addActionListener(mainFrame.getMenuPanel());
        exitButton.addActionListener(mainFrame.getMenuPanel());
        settingsButton.addActionListener(mainFrame.getMenuPanel());
        basketButton.addActionListener(mainFrame.getMenuPanel());
        comparisonButton.addActionListener(mainFrame.getMenuPanel());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        partsButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        basketButton = new javax.swing.JButton();
        discountSpinnerLabel = new javax.swing.JLabel();
        discountSpinner = new javax.swing.JSpinner();
        accessoriesButton = new javax.swing.JButton();
        tabsLabel = new javax.swing.JLabel();
        menuLabel = new javax.swing.JLabel();
        comparisonButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        acceptButton = new javax.swing.JButton();

        partsButton.setText("jButton1");

        settingsButton.setText("jButton1");

        exitButton.setText("jButton1");

        basketButton.setText("jButton1");

        discountSpinnerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        accessoriesButton.setText("jButton1");

        tabsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        menuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        comparisonButton.setText("jButton1");

        backButton.setText("jButton1");

        acceptButton.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comparisonButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accessoriesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discountSpinnerLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(basketButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settingsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(discountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(acceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(discountSpinnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(discountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tabsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(partsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accessoriesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(menuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(basketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comparisonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(359, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton accessoriesButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton basketButton;
    private javax.swing.JButton comparisonButton;
    private javax.swing.JSpinner discountSpinner;
    private javax.swing.JLabel discountSpinnerLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JButton partsButton;
    private javax.swing.JButton settingsButton;
    private javax.swing.JLabel tabsLabel;
    // End of variables declaration//GEN-END:variables
}
