/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import frame.MainFrame;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Stroke;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author sluja
 */
public class LoadingPanel extends javax.swing.JPanel implements Runnable {

    private int  centerW = 0, centerH = 0, barSizeWidth = 0, barSizeHeight = 0, barPosX = 0, barPosY = 0, counter = 0;
    private MainFrame mainFrame;
    
    public LoadingPanel(MainFrame frame) {

        this.mainFrame = frame;
        this.centerW = frame.getElementOneWidth()/2;
        this.centerH = frame.getElementOneHeight()/2;
        this.barSizeWidth = this.centerW/2;
        this.barSizeHeight = this.centerH/6;
        this.barPosX = this.centerW - this.barSizeWidth;
        this.barPosY = this.centerH - this.barSizeHeight;
        Thread thr = new Thread(this);
        thr.start();
        
    }
    
    private Color getBackgroundColor()
    {
        return this.mainFrame.getPanelBackground();
    }
    
    private void redraw()
    {
     counter += 1;
     this.repaint();
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            this.redraw();
        }
    }
    
   @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        
        Graphics2D painter = (Graphics2D) g;
        painter.setStroke(new BasicStroke(10));
        
        if(getBackgroundColor() == Color.BLACK) painter.setColor(Color.WHITE);
        else painter.setColor(Color.BLACK);
        
        painter.drawRect(barPosX, barPosY, barSizeWidth, barSizeHeight);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void run(){
        if(counter <= 5) redraw();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
