/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import classes.DatabaseHandler;
import classes.ShopResearcher;
import frame.BasketMainFrame;
import frame.MainFrame;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author sluja
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    final String TABLE_NAME = "BasketTable";
    
    MainFrame frame;
    private String nameOfShop = "";
    private String nameOfPart = "";
    private int shopNumber = 0;
    
    private BasketMainFrame basketFrame;
    ShopResearcher shopResearcher;
    private boolean partSearched = false;
    
    //Initialize database handler
    private DatabaseHandler databaseHandler = new DatabaseHandler();
    
    
    
    
    public MainPanel( MainFrame frame, boolean tableExists) {
        
        this.frame = frame;
        this.setSize(frame.getElementOneWidth(), frame.getElementOneHeight());
        //databaseHandler.setMainPanel(this);
        basketFrame = new BasketMainFrame(this);
        if(!tableExists) databaseHandler.createTable(TABLE_NAME);
        databaseHandler.deleteAllElements(TABLE_NAME);
        initComponents(); 
        setButtonText();
        
    }
    

    
    public String getTableName()
    {
        return this.TABLE_NAME;
    }
    
    public void setButtonText()
    {
        this.shopLabel.setText(this.getFrame().getResourceBundle().getString("shop"));
        this.barendsButton.setText(this.getFrame().getResourceBundle().getString("barends"));
        this.barsButton.setText(this.getFrame().getResourceBundle().getString("bars"));
        this.stemsButton.setText(this.getFrame().getResourceBundle().getString("stems"));
        this.gripsButton.setText(this.getFrame().getResourceBundle().getString("grips"));
        this.steersButton.setText(this.getFrame().getResourceBundle().getString("steers"));
        this.forksButton.setText(this.getFrame().getResourceBundle().getString("forks"));
        this.tyresButton.setText(this.getFrame().getResourceBundle().getString("tires"));
        this.hubsButton.setText(this.getFrame().getResourceBundle().getString("hubs"));
        this.spokesButton.setText(this.getFrame().getResourceBundle().getString("spokes"));
        this.hubguardsButton.setText(this.getFrame().getResourceBundle().getString("hubguards"));
        this.cranksButton.setText(this.getFrame().getResourceBundle().getString("cranks"));
        this.chainButton.setText(this.getFrame().getResourceBundle().getString("chains"));
        this.chainwheelsButton.setText(this.getFrame().getResourceBundle().getString("sprockets"));
        this.pedalsButton.setText(this.getFrame().getResourceBundle().getString("pedals"));
        this.seatpostsButton.setText(this.getFrame().getResourceBundle().getString("posts"));
        this.seatsButton.setText(this.getFrame().getResourceBundle().getString("seats"));
        this.supportsButton.setText(this.getFrame().getResourceBundle().getString("supports"));
        this.pegsButton.setText(this.getFrame().getResourceBundle().getString("pegs"));
        this.rimsButton.setText(this.getFrame().getResourceBundle().getString("rims"));
        this.framesButton.setText(this.getFrame().getResourceBundle().getString("frames"));
        repaint();
    }
    
    public DatabaseHandler getDatabaseHandler()
    {
        return this.databaseHandler;
    }

    public MainFrame getFrame()
    {
        return this.frame;
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        barsButton = new javax.swing.JButton();
        shopLabel = new javax.swing.JLabel();
        bmxlifeCheckBox = new javax.swing.JCheckBox();
        manyfestCheckBox = new javax.swing.JCheckBox();
        avebmxCheckBox = new javax.swing.JCheckBox();
        alldayCheckBox = new javax.swing.JCheckBox();
        hubguardsButton = new javax.swing.JButton();
        chainwheelsButton = new javax.swing.JButton();
        chainButton = new javax.swing.JButton();
        steersButton = new javax.swing.JButton();
        pegsButton = new javax.swing.JButton();
        barendsButton = new javax.swing.JButton();
        forksButton = new javax.swing.JButton();
        hubsButton = new javax.swing.JButton();
        spokesButton = new javax.swing.JButton();
        seatsButton = new javax.swing.JButton();
        stemsButton = new javax.swing.JButton();
        supportsButton = new javax.swing.JButton();
        cranksButton = new javax.swing.JButton();
        rimsButton = new javax.swing.JButton();
        tyresButton = new javax.swing.JButton();
        seatpostsButton = new javax.swing.JButton();
        pedalsButton = new javax.swing.JButton();
        framesButton = new javax.swing.JButton();
        gripsButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(null);

        barsButton.setText("KIEROWNICE");
        barsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barsButtonActionPerformed(evt);
            }
        });
        add(barsButton);
        barsButton.setBounds(380, 60, 140, 30);

        shopLabel.setText("Sklepy:");
        add(shopLabel);
        shopLabel.setBounds(20, 650, 60, 16);

        buttonGroup.add(bmxlifeCheckBox);
        bmxlifeCheckBox.setText("BmxLife");
        bmxlifeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmxlifeCheckBoxActionPerformed(evt);
            }
        });
        add(bmxlifeCheckBox);
        bmxlifeCheckBox.setBounds(90, 660, 110, 20);

        buttonGroup.add(manyfestCheckBox);
        manyfestCheckBox.setText("ManyfestBmx");
        manyfestCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manyfestCheckBoxActionPerformed(evt);
            }
        });
        add(manyfestCheckBox);
        manyfestCheckBox.setBounds(200, 630, 130, 20);

        buttonGroup.add(avebmxCheckBox);
        avebmxCheckBox.setText("AveBmx");
        avebmxCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avebmxCheckBoxActionPerformed(evt);
            }
        });
        add(avebmxCheckBox);
        avebmxCheckBox.setBounds(90, 630, 110, 20);

        buttonGroup.add(alldayCheckBox);
        alldayCheckBox.setText("AlldayBmx");
        alldayCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alldayCheckBoxActionPerformed(evt);
            }
        });
        add(alldayCheckBox);
        alldayCheckBox.setBounds(200, 660, 130, 20);

        hubguardsButton.setText("HUBGUARDY");
        hubguardsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hubguardsButtonActionPerformed(evt);
            }
        });
        add(hubguardsButton);
        hubguardsButton.setBounds(470, 460, 130, 30);

        chainwheelsButton.setText("ZĘBATKI");
        chainwheelsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chainwheelsButtonActionPerformed(evt);
            }
        });
        add(chainwheelsButton);
        chainwheelsButton.setBounds(180, 430, 120, 30);

        chainButton.setText("ŁAŃCUCHY");
        chainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chainButtonActionPerformed(evt);
            }
        });
        add(chainButton);
        chainButton.setBounds(150, 370, 110, 30);

        steersButton.setText("STERY");
        steersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                steersButtonActionPerformed(evt);
            }
        });
        add(steersButton);
        steersButton.setBounds(470, 240, 90, 30);

        pegsButton.setText("PEGI");
        pegsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pegsButtonActionPerformed(evt);
            }
        });
        add(pegsButton);
        pegsButton.setBounds(50, 420, 100, 30);

        barendsButton.setText("BARENDY");
        barendsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barendsButtonActionPerformed(evt);
            }
        });
        add(barendsButton);
        barendsButton.setBounds(550, 50, 120, 30);

        forksButton.setText("WIDELCE");
        forksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forksButtonActionPerformed(evt);
            }
        });
        add(forksButton);
        forksButton.setBounds(410, 350, 100, 30);

        hubsButton.setText("PIASTY");
        hubsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hubsButtonActionPerformed(evt);
            }
        });
        add(hubsButton);
        hubsButton.setBounds(480, 420, 100, 30);

        spokesButton.setText("SZPRYCHY");
        spokesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spokesButtonActionPerformed(evt);
            }
        });
        add(spokesButton);
        spokesButton.setBounds(440, 530, 120, 30);

        seatsButton.setText("SIODEŁKO");
        seatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatsButtonActionPerformed(evt);
            }
        });
        add(seatsButton);
        seatsButton.setBounds(200, 230, 120, 30);

        stemsButton.setText("MOSTKI");
        stemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stemsButtonActionPerformed(evt);
            }
        });
        add(stemsButton);
        stemsButton.setBounds(420, 150, 100, 30);

        supportsButton.setText("SUPPORTY");
        supportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supportsButtonActionPerformed(evt);
            }
        });
        add(supportsButton);
        supportsButton.setBounds(300, 390, 130, 30);

        cranksButton.setText("KORBY");
        cranksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cranksButtonActionPerformed(evt);
            }
        });
        add(cranksButton);
        cranksButton.setBounds(270, 470, 100, 30);

        rimsButton.setText("OBRĘCZE");
        rimsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rimsButtonActionPerformed(evt);
            }
        });
        add(rimsButton);
        rimsButton.setBounds(120, 490, 110, 30);

        tyresButton.setText("OPONY");
        tyresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tyresButtonActionPerformed(evt);
            }
        });
        add(tyresButton);
        tyresButton.setBounds(560, 370, 90, 30);

        seatpostsButton.setText("SZTYCE");
        seatpostsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatpostsButtonActionPerformed(evt);
            }
        });
        add(seatpostsButton);
        seatpostsButton.setBounds(210, 280, 110, 30);

        pedalsButton.setText("PEDAŁY");
        pedalsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedalsButtonActionPerformed(evt);
            }
        });
        add(pedalsButton);
        pedalsButton.setBounds(310, 320, 100, 30);

        framesButton.setText("RAMY");
        framesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                framesButtonActionPerformed(evt);
            }
        });
        add(framesButton);
        framesButton.setBounds(340, 230, 90, 30);

        gripsButton.setText("GRIPY");
        add(gripsButton);
        gripsButton.setBounds(260, 20, 90, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bmxIconR.PNG"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(10, 10, 620, 640);
    }// </editor-fold>//GEN-END:initComponents

    private void barsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barsButtonActionPerformed
   
        setPartName("kierownice");
    }//GEN-LAST:event_barsButtonActionPerformed

    private void avebmxCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avebmxCheckBoxActionPerformed
        setShop("avebmx",2);
    }//GEN-LAST:event_avebmxCheckBoxActionPerformed

    private void bmxlifeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmxlifeCheckBoxActionPerformed
         setShop("bmxlife",1);
    }//GEN-LAST:event_bmxlifeCheckBoxActionPerformed

    private void manyfestCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manyfestCheckBoxActionPerformed
        setShop("manyfestbmx",3);
    }//GEN-LAST:event_manyfestCheckBoxActionPerformed

    private void alldayCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alldayCheckBoxActionPerformed
         setShop("allday",4);
    }//GEN-LAST:event_alldayCheckBoxActionPerformed
 
    private void framesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_framesButtonActionPerformed
        setPartName("ramy");
    }//GEN-LAST:event_framesButtonActionPerformed

    private void tyresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tyresButtonActionPerformed
        setPartName("opony");
    }//GEN-LAST:event_tyresButtonActionPerformed

    private void rimsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rimsButtonActionPerformed
        setPartName("obrecze");
    }//GEN-LAST:event_rimsButtonActionPerformed

    private void cranksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cranksButtonActionPerformed
        setPartName("korby");
    }//GEN-LAST:event_cranksButtonActionPerformed

    private void supportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supportsButtonActionPerformed
        setPartName("suporty");
    }//GEN-LAST:event_supportsButtonActionPerformed

    private void stemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stemsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stemsButtonActionPerformed

    private void seatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatsButtonActionPerformed
        setPartName("siodelka");
    }//GEN-LAST:event_seatsButtonActionPerformed

    private void spokesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spokesButtonActionPerformed
        setPartName("szprychy");
    }//GEN-LAST:event_spokesButtonActionPerformed

    private void hubsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hubsButtonActionPerformed
        setPartName("piasty");
    }//GEN-LAST:event_hubsButtonActionPerformed

    private void forksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forksButtonActionPerformed
        setPartName("widelce");
    }//GEN-LAST:event_forksButtonActionPerformed

    private void barendsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barendsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barendsButtonActionPerformed

    private void pegsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pegsButtonActionPerformed
        setPartName("pegi");
    }//GEN-LAST:event_pegsButtonActionPerformed

    private void steersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_steersButtonActionPerformed
        setPartName("stery");
    }//GEN-LAST:event_steersButtonActionPerformed

    private void chainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chainButtonActionPerformed
        setPartName("lancuchy");
    }//GEN-LAST:event_chainButtonActionPerformed

    private void chainwheelsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chainwheelsButtonActionPerformed
        setPartName("zebatki");
    }//GEN-LAST:event_chainwheelsButtonActionPerformed

    private void hubguardsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hubguardsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hubguardsButtonActionPerformed

    private void seatpostsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatpostsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatpostsButtonActionPerformed

    private void pedalsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedalsButtonActionPerformed
        setPartName("pedaly");
    }//GEN-LAST:event_pedalsButtonActionPerformed

    public BasketMainFrame getBasketFrame()
    {
        return basketFrame;
    }
    
    private String[] getHTMLElements(String namePart, int shopNumber,int pageNumber)
    {
           URL url = this.getClass().getClassLoader().getResource("properties/info.txt");
           
           File file = new File(url.getFile());
       
           BufferedReader br;
           String[] part = new String[3];
           int lineNumber = 1;
           
           
           try {
            br = new BufferedReader(new FileReader(file)); 
            String st;
            
            while ((st = br.readLine()) != null)
            {  
                if(lineNumber == shopNumber)
                {
                    part = st.split(";");
                    System.out.println(part[0]);
                    System.out.println(part[1]);
                    System.out.println(part[2]);
                    System.out.println(part[3]);
                    System.out.println(part[4]);
                    break;
                }
                
                lineNumber += 1;
            }
            
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MainPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
           
            part[0] = part[0] + namePart; 
            
            switch(shopNumber)
            {
                case 1: break;
                case 2:
                {
                    part[0] = part[0] + "?page=" + pageNumber;
                    break;
                }
                case 3:
                {
                    part[0] = part[0] + "-bmx?resultsPerPage=99999";
                }
            }
             
           return part;
       }
    
       private void setResearcher()
       {
           setResearcher(nameOfPart, nameOfShop, shopNumber);
       }
       
       private void setResearcher(String namePart, String nameShop, int shopNumber)
       {
        String[] parts = getHTMLElements(namePart,shopNumber,1);
        
        String html = parts[0];
        String[] htmlElements = {parts[1],parts[2],parts[3],parts[4]};
        shopResearcher = new ShopResearcher(html, nameShop, 2);
        if(!this.getFrame().productTableExists()) 
        {
            shopResearcher.createTable();
            this.getFrame().getFilesHandler().writeToFile("true;", 2);
        }
        else shopResearcher.getProductDatabaseHandler().deleteAllElements(shopResearcher.getProductDatabaseHandler().getTableTitle());
        shopResearcher.setFrame(this.frame);
        shopResearcher.setCategory(namePart);
        shopResearcher.setConnection();
        shopResearcher.initializeArrayOfElements(htmlElements);
        shopResearcher.searchHTMLElements();
        shopResearcher.initializePartPanel();
        partSearched = true;
       }
       
       public void setHTML(String html)
       {
           
       }
       
       public boolean getSearchState()
       {
           return this.partSearched;
       }
       
       public ShopResearcher getResearcher()
       {
           return this.shopResearcher;
       }
       
       private void setPartName(String name)
       {
           this.nameOfPart = name;
           if(avebmxCheckBox.isSelected() || bmxlifeCheckBox.isSelected() || manyfestCheckBox.isSelected() || alldayCheckBox.isSelected()) setResearcher(nameOfPart,nameOfShop,shopNumber);
       }
       
       public String getPartName()
       {
           return this.nameOfPart;
       }
       
       private void setShop(String name, int number)
       {
           this.nameOfShop = name;
           this.shopNumber = number;
       }

       public String getShopName()
       {
           return this.nameOfShop;
       }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox alldayCheckBox;
    private javax.swing.JCheckBox avebmxCheckBox;
    private javax.swing.JButton barendsButton;
    private javax.swing.JButton barsButton;
    private javax.swing.JCheckBox bmxlifeCheckBox;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton chainButton;
    private javax.swing.JButton chainwheelsButton;
    private javax.swing.JButton cranksButton;
    private javax.swing.JButton forksButton;
    private javax.swing.JButton framesButton;
    private javax.swing.JButton gripsButton;
    private javax.swing.JButton hubguardsButton;
    private javax.swing.JButton hubsButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JCheckBox manyfestCheckBox;
    private javax.swing.JButton pedalsButton;
    private javax.swing.JButton pegsButton;
    private javax.swing.JButton rimsButton;
    private javax.swing.JButton seatpostsButton;
    private javax.swing.JButton seatsButton;
    private javax.swing.JLabel shopLabel;
    private javax.swing.JButton spokesButton;
    private javax.swing.JButton steersButton;
    private javax.swing.JButton stemsButton;
    private javax.swing.JButton supportsButton;
    private javax.swing.JButton tyresButton;
    // End of variables declaration//GEN-END:variables
}
