/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import frame.MainFrame;
import java.awt.Dimension;

/**
 *
 * @author krzysztof.sluja
 */
public class WearPanel extends javax.swing.JPanel {

    /**
     * Creates new form WearPanel
     */
    private String page, html;
    MainFrame frame;
    
    public WearPanel(MainFrame frame) {
       
        this.frame = frame;
        this.setPreferredSize(new Dimension(frame.getElementOneWidth(), frame.getElementOneHeight()));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helmetButton = new javax.swing.JButton();
        padsButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 800));
        setLayout(null);

        helmetButton.setText("KASKI");
        helmetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helmetButtonActionPerformed(evt);
            }
        });
        add(helmetButton);
        helmetButton.setBounds(50, 40, 120, 30);

        padsButton.setText("OCHRANIACZE");
        padsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                padsButtonActionPerformed(evt);
            }
        });
        add(padsButton);
        padsButton.setBounds(50, 80, 120, 30);

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(50, 130, 73, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void helmetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helmetButtonActionPerformed
        System.out.println("JESTEM TU");
        //setHTML("kaski");
        System.out.println("HTML KASKI: " + getHTML());
        frame.getMainPanel().setPartName("kaski", false);
    }//GEN-LAST:event_helmetButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void padsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_padsButtonActionPerformed
        System.out.println("JESTEM TU");
        //setHTML("kaski");
        System.out.println("HTML OCHRONKI: " + getHTML());
        frame.getMainPanel().setPartName("ochraniacze", false);
    }//GEN-LAST:event_padsButtonActionPerformed

    public void setPage(String page){
        this.page = page;
        System.out.println("WEAR PANEL PAGE" + page);
    }
    
    public void setHTML(String part){
        this.html = this.page + part;
    }
    
    public String getHTML(){
        return this.html;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton helmetButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton padsButton;
    // End of variables declaration//GEN-END:variables
}
