/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import panel.ComparisonPanel;
import panel.MainPanel;
import panel.SearchPanel;
import panel.UserPanel;

/**
 *
 * @author sluja
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    int width = 800;
    int height = 800;
    int xPosition = Toolkit.getDefaultToolkit().getScreenSize().width/2 - width/2;
    int yPosition = Toolkit.getDefaultToolkit().getScreenSize().height/2 - height/2;
    String language;
    
    BorderLayout mainFrameLayout = new BorderLayout();
    UserPanel userPanel;
    MainPanel mainPanel;
    SearchPanel searchPanel;
    ComparisonPanel comparisonPanel;
    
    
    
    
    public MainFrame()
    {
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setBounds(xPosition,yPosition,width,height);
        this.setLayout(mainFrameLayout);
        this.setPreferredSize(new Dimension(width,height));
        this.setResizable(false);
        
    }

    public void setMainFeature()
    {
        userPanel = new UserPanel(this);
        mainPanel = new MainPanel(this);
        searchPanel = new SearchPanel(this);
        this.comparisonPanel = new ComparisonPanel(this.width, this.height, this);
        
        searchPanel.setVisible(false);
      
        this.getContentPane().add(userPanel, mainFrameLayout.EAST);
        this.getContentPane().add(mainPanel, mainFrameLayout.CENTER);
        this.getContentPane().add(searchPanel, BorderLayout.NORTH);
        this.getContentPane().add(this.comparisonPanel, mainFrameLayout.CENTER);
        this.comparisonPanel.setVisible(false);
        
        
    }
    
    public void addPanelToFrame(Component object, String location)
    {
        if(location.equals("north")) this.getContentPane().add(object, mainFrameLayout.NORTH);
    }
    
    public void setComparisonVisible()
    {
        this.comparisonPanel.setVisible(true);
        this.userPanel.setVisible(false);
    }
    
    public UserPanel getUserPanel()
    {
        return this.userPanel;
    }
    
    public void setElementVisible(boolean flag)
    {
        searchPanel.setVisible(flag);
    }
    
    public int getAppWidth()
    {
        return this.width;
    }
    public int getAppHeight()
    {
        return this.height;
    }
    
    public ComparisonPanel getComparisonPanel()
    {
        return this.comparisonPanel;
    }
    
    public void setLanguage(String language)
    {
        this.language = language;
    }
    
    public String getLanguage()
    {
        return this.language;
    }
    
    public BorderLayout getFrameLayout()
    {
        return this.mainFrameLayout;
    }
    
    public MainPanel getMainPanel()
    {
        return this.mainPanel;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
